import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Provider from "@/utils/providers";
import SliderSection from "@/components/features/home/Sliders/SliderSection";
import DynamicBanner from "@/components/features/shared/banner/DynamicBanner";
import SubscribeSection from "@/components/features/subscribe/SubscribeSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <>

      <Provider>
        <DynamicBanner />
        <SliderSection />
        {children}

        <SubscribeSection />

      </Provider>
    </>
  );
}
