import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import Provider from "@/utils/providers";
import NavBar from "@/components/features/shared/NavBar";
import SliderSection from "@/components/features/home/Sliders/SliderSection";
import SubscribeSection from "@/components/features/subscribe/SubscribeSection";
import Footer from "@/components/features/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <NavBar />
          <SliderSection />
          {children}
          <SubscribeSection />
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
